version: "3.9"

services:
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp/monitoring:latest  # Valid image name with repository and tag
    container_name: productivity
    expose:
      - "5001"  # Internal port for Nginx
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=5001
    # Remove 'command' if Dockerfile CMD is identical
    # command: uvicorn main:app --host ${UVICORN_HOST} --port ${UVICORN_PORT}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]  # Adjust to your app's health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # External port for users
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      monitoring:
        condition: service_healthy  # Wait for monitoring to be healthy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge